### ISSUE TITLE
TB Boost behaving inconsistently after sleep+unlock

### ISSUE THREAD

**Issue by igor-makarov** [rugarciap/Turbo-Boost-Switcher#108]
Hi all,

First of all, let me say that I did skim the other "similar issues" and I think this is a different thing.  Additionally, I don't feel like running the app as a system agent, as some answers suggest.

Second of all, I don't mind entering the password when enabling/disabling if it indeed happens upon user action.

On to the issue itself. Steps to reproduce:

* Disable turbo boost. System prompts for password - enter password. Turbo boost gets disabled. Confirmed by `kextstat`.
* Make the computer go to sleep by closing the lid. Walk to the rail station for 15 minutes.
* Open the lid and unlock the computer using TouchID/Apple Watch.
* System prompts for password, unexpectedly.   
**Important: Press 'Cancel', multiple times, until password prompts stop.** 

**After this, the turbo boost actually stays disabled!**   
Running `kextstat` confirms this.  
This is why I think this is a different thing.

My system:
* MacBook Pro (15-inch, 2017)
* 2.9 GHz Quad-Core Intel Core i7
* Catalina 10.15.3 (19D76)

Thanks for making this app and making my laptop much less of a fire hazard 😂🧯.

**Comment by rugarciap** [comment]
Hi!

Why did you press cancel? All kext need root privileges in order to be loaded, that's why the app is asking for that. If you don't enter your root password, the kext won't load.

As detailed on other entries, after coming back from sleep, the kext is always reloaded (depending on your settings) since OSX sometimes re-enable Turbo Boost automatically. This has been since first releases...., and since OSX "forgets" authorisations after some time, that's why it requests again for root password.

There are a lot of workarounds to this like detailed on some other entries, and of course also getting the pro version that uses another way of authorising as a way to give something in return for supporting the app development.

Thanks and best regards.
