### ISSUE TITLE
Official Turbo Boost Switcher binary contains unsigned kext

### ISSUE THREAD

**Issue by desowin** [rugarciap/Turbo-Boost-Switcher#114]
Does not work on macOS Catalina with the system protection enabled.

`Defaulting to kernel file '/System/Library/Kernels/kernel'
kext file:///Library/StagedExtensions/Applications/Turbo%20Boost%20Switcher.app/Contents/Resources/DisableTurboBoost.64bits.kext/ is in hash exception list, allowing to load
Kext rejected due to system policy: <OSKext 0x7f8832545eb0 [0x7fff8935e8c0]> { URL = "file:///Library/StagedExtensions/Applications/Turbo%20Boost%20Switcher.app/Contents/Resources/DisableTurboBoost.64bits.kext/", ID = "com.rugarciap.DisableTurboBoost" }
Code Signing Failure: not code signed
Diagnostics for /Applications/Turbo Boost Switcher.app/Contents/Resources/DisableTurboBoost.64bits.kext:
`

**Comment by rugarciap** [comment]
Wrong.., the kext is explicity allowed by Apple, as you can read on the log, and in fact the kext works even on latest beta:

**is in hash exception list, allowing to load Kext** 

You're missing user validation properly, that's why it fails to load. If you need support about how to do this, you can reach me at my email address, shared on the blog.

Thanks!

Closing..
