### ISSUE TITLE
Password prompts in pro version?

### ISSUE THREAD

**Issue by patik** [rugarciap/Turbo-Boost-Switcher#12]
Does the pro version still prompt for an admin password every time you open the lid of your MacBook, like the free version does?

**Comment by kjs3** [comment]
Bump. 

That would get me to buy. ;)

**Comment by csepulv** [comment]
That would also get me to buy

**Comment by rugarciap** [comment]
Turbo Boost Switcher installs a kernel extension and that operation needs to be done by an admin user (or root) in order to do that. The user you choose to run the app must be also capable of gaining root permissions (sudoers list) in order to change file permissions, since apple forces the kext file to be owned by the user root.

This is not an issue, is just a requirement and a security configuration Apple forces. Review your user permissions and if all is fine then the app won't ask the root password more than once per session.

Best!
