### ISSUE TITLE
App not working on 10.15.6

### ISSUE THREAD

**Issue by vinayakg** [rugarciap/Turbo-Boost-Switcher#135]
Hi
Could you please let know if there is a way to make this work on 10.15.6. I tried downloading the app from brew, it failed to work, the process is seen in Activity Monitor but the UI does not load. I also tried downloading from website, unzip and then copy over to Applications. Same result. 

I tried running this command(`sudo kextutil -v /Applications/Turbo\ Boost\ Switcher.app/Contents/Resources/DisableTurboBoost.64bits.kext`) to just check the output and it failed with the below error. Tried to find what the command does - out of curiosity.

```
sudo kextutil -v /Applications/Turbo\ Boost\ Switcher.app/Contents/Resources/DisableTurboBoost.64bits.kext
Defaulting to kernel file '/System/Library/Kernels/kernel'
kext file:///private/var/db/KernelExtensionManagement/Staging/tmp.HYtQiJ/258332E8-815B-4F8B-BD1B-96008C68454B.kext/ is in hash exception list, allowing to load
Kext rejected due to improper filesystem permissions: <OSKext 0x7fa7e7717aa0 [0x7fff88a50cc0]> { URL = "file:///Library/StagedExtensions/Applications/Turbo%20Boost%20Switcher.app/Contents/Resources/DisableTurboBoost.64bits.kext/", ID = "com.rugarciap.DisableTurboBoost" }
Code Signing Failure: not code signed
Authentication Failures:
    File owner/permissions are incorrect (must be root:wheel, nonwritable by group/other):
        /Library/StagedExtensions/Applications/Turbo Boost Switcher.app/Contents/Resources/DisableTurboBoost.64bits.kext
        Contents
        MacOS
        DisableTurboBoost
        Info.plist~
        Info.plist
```

I am pasting the snapshot of my Activity monitor output. Please let me know how this can be resolved

![image](https://user-images.githubusercontent.com/1701204/88711583-02954e80-d136-11ea-940b-463f7b8aed5e.png)

**Comment by rugarciap** [comment]
Hi!

The install seems messed up.., as you can see, the log is reporting incorrect permissions, and that's accomplished by the app the first time it runs after authorising.

Please, follow the next steps in order to reinstall the app. If you need further help, reach me at my contact address shown at in the blog (rugarciap.com)

1.- Stop / Quit the app.
2.- Drag to the trash the .app file.
3.- Open the original .zip and install the app again by dragging it to Applications folder (this step is very important…, if you run the app directly from the unziped folder will not work due to some strange feature Apple introduced they call translocation).
4.- When asked, enter your root password.
5.- Click on “Disable Turbo Boost” manually to force the kext to load. If still “On”, go to Security prefs and allow the kext to be loaded (clicking allow and enabling “rugarciap” software). After that, you can reboot to be sure the changes are applied.
7.- Try refreshing the status bar by clicking twice over it.

You can also execute in the terminal “kextstat” and search for the extension (com.rugarciap…). If it’s loaded then it means TB is off.

Best!
