### ISSUE TITLE
Prompted for password after sleep/wake/unlocking.

### ISSUE THREAD

**Issue by Xuff** [rugarciap/Turbo-Boost-Switcher#14]
Every time my Mac sleeps and is woken up I'm prompted to enter my administrator credentials for Turbo Boost Switcher.  Because the Turbo Boost Switcher process is constantly running I would only expect to have to do this when it's initially launched.

I have a MacBook Pro (Retina, 15-inch, Mid 2014) running 10.10.5, although this issue existed on previous versions of Yosemite as well.

**Comment by Xuff** [comment]
Here's what happens in Console when I close the lid, open it, unlock, and enter the password to authorize Turbo Boost Switcher:

    8/30/15 1:01:12.348 PM Turbo Boost Switcher[1006]: kextstat output:   157    0 0xffffff7f82f41000 0x2000     0x2000     com.rugarciap.DisableTurboBoost (0.0.1) <7 5 4 1>
    8/30/15 1:01:39.000 PM kernel[0]: Re-enabled Turbo Boost: 4000850089 -> 850089
    8/30/15 1:01:40.000 PM kernel[0]: Disabled Turbo Boost: 850089 -> 4000850089
    8/30/15 1:01:40.491 PM Turbo Boost Switcher[1006]: kextstat output:   162    0 0xffffff7f82f41000 0x2000     0x2000     com.rugarciap.DisableTurboBoost (0.0.1) <7 5 4 1>

**Comment by zeckalpha** [comment]
I've got the same issue. This also seems to be indirectly asked for in #12.

**Comment by vikbez** [comment]
That would be perfect if this wasn't needed.
(same issue in 10.9.4)

**Comment by StephanOnTour** [comment]
https://github.com/rugarciap/Turbo-Boost-Switcher/issues/4

**Comment by rugarciap** [comment]
Turbo Boost Switcher installs a kernel extension and that operation needs to be done by an admin user (or root) in order to do that. The user you choose to run the app must be also capable of gaining root permissions (sudoers list) in order to change file permissions, since apple forces the kext file to be owned by the user root.

This is not an issue, is just a requirement and a security configuration Apple forces. Review your user permissions and if all is fine then the app won't ask the root password more than once per session.

Best!

**Comment by shoryamalani** [comment]
Hey guys this solution is actually pretty simple. After driving myself nuts I found out all you need to do is go into the package contents, go into resources, and change the owner of DisableTurboBoost.64bits.kext to the account you are logging into. Now restart the app and problem solved.
