### ISSUE TITLE
High Frequency at idle 

### ISSUE THREAD

**Issue by nicolacana** [rugarciap/Turbo-Boost-Switcher#148]
I have a problem once I get the Pro version.
When TB Is disabled it’s all ok,
when I enable it I saw cpu running always high frequency (properly at max freq.) without any load (6%).

I think is a bug of tbs pro and also deleting it, the problem persist.

Now I have that MacBook reaches 99°C at idle with tb enabled (which should be default).

Please help me 
I have a MacBook 16 i9 2019
thank you 

<img width="425" alt="Screenshot 2020-10-24 at 11 40 00" src="https://user-images.githubusercontent.com/72206529/97078631-c0bd5c80-15ed-11eb-8764-229435b2d4c6.png">
<img width="408" alt="Screenshot 2020-10-24 at 11 40 17" src="https://user-images.githubusercontent.com/72206529/97078634-c450e380-15ed-11eb-9785-185437cc856f.png">
<img width="988" alt="Screenshot 2020-10-24 at 11 40 29" src="https://user-images.githubusercontent.com/72206529/97078636-c61aa700-15ed-11eb-8886-9cb192f5d3ab.png">

**Comment by rugarciap** [comment]
Hi,

Although this is a support question and this is for issues with the open source and free one, answering here to clarify, since what I'm going to tell below is the same for both versions.

When you quit the app, the kext is unloaded (you can verify this by running kextstat command and search for com.rugarciap.DisableTurboBoost) so the CPU gets back to its default status..., that is, Turbo Boost enabled (not activated, since that is managed exclusively by CPU itself).

In fact, when you enable Turbo Boost, it's still the CPU who decides when to activate Turbo Boost or not depending on CPU load, temperature, etc... and when loaded, kext doesn't perform any CPU intensive task, it "just" flag the MSR register of the CPU in order to disable Turbo Boost.

It can be spotlight or any other process, but not Turbo Boost.

Thanks for supporting and your feedback.

**Comment by rugarciap** [comment]
For any other support question, you can reach me directly to the email address given at Gumroad receipt.
