### ISSUE TITLE
Kext not loadable

### ISSUE THREAD

**Issue by FuocomanSap** [rugarciap/Turbo-Boost-Switcher#149]
Big Sur 11.0.1
MBP 15 2019,i9
TBS Pro v2.10.1

after "disable turbo boost" or after "sudo kextutil -v /Applications/tbswitcher_resources/DisableTurboBoost.64bits.kext"
I get this error on the "kmutil log stream" :
"
Defaulting to kernel file '/System/Library/Kernels/kernel'
Executing: /usr/bin/kmutil load --bundle-path /Applications/tbswitcher_resources/DisableTurboBoost.64bits.kext
Kernel request failed: (libkern/kext) not loadable (reason unspecified) (-603946989)
"

**Comment by rugarciap** [comment]
Hi,

The kext works fine with BigSur, but when updating issues can appear due to how Apple changed kext loading process. You're being unable to load the kext probably due to some issue with staging, permissions, user approval, or any other of the restrictions imposed by Apple to load kexts.

A lot of troubleshooting was added to the help file included with the download image. Please, try that, and if you need more support, you can always reach me at the email address included here: rugarciap.com/faqs

Best.
