### ISSUE TITLE
Path not found - Big Sur 11.0.1

### ISSUE THREAD

**Issue by chonsser** [rugarciap/Turbo-Boost-Switcher#153]
After upgrading to Big Sur I saw the switcher doesn't work anymore. I tried to remove the app and download again but got such an error:
![image](https://user-images.githubusercontent.com/10325355/101604512-5297f200-3a01-11eb-9257-c05767a44ab4.png)
I saw no info about such a case in FAQ. 

Using the lastest Turbo Boost Switcher Pro (`Turbo_Boost_Switcher_Pro_v2.10.1`)

**Comment by rugarciap** [comment]
Hi!

You're suffering from Translocation. Please, open the HELP file included with the distribution and follow the steps detailed there. If you need more support, please, reach me by answering to the Gumroad's receipt, since this is for issues with the app please.

Thanks for supporting and best regards!
