### ISSUE TITLE
kernelmanagerd takes 100% of CPU when Turbo Switcher Pro is on, reduces battery life by 70%

### ISSUE THREAD

**Issue by chara1ampos** [rugarciap/Turbo-Boost-Switcher#158]
Turbo Switcher Pro is **not compatible with Mac OS Big Sur** 11.0.1 or 11.1.
Certain problematic applications cause the **kernelmanagerd** process to highjack 100% of CPU.
[https://discussions.apple.com/thread/252033284](https://discussions.apple.com/thread/252033284)
Turbo Switcher Pro is one of those problematic applications.
On a 16" MacBook Pro, when Turbo Switcher Pro is on, **kernelmanagerd** jumps to **50-100% of CPU**, **power consumption** goes up to **20-50 Watts**, **battery life decreases to 2-3 hours**, and **fans spin audibly faster**.
As soon as I quit Turbo Switcher Pro, all is normal: kernelmanagerd goes back to 0% of CPU, power consumption goes back to 5-10 Watts, battery life goes back to 9-10 hours, and fans are quiet.
It is a bit ironic that Turbo Switcher Pro claims to improve battery performance, when in fact it drains the battery 3 times faster, causing premature wear and tear to your battery and hardware. **This must be addressed urgently.**

**Comment by rugarciap** [comment]
Hi,

The kext included with the app is only loaded once when disabling turbo boost, and there is no interaction more than that with the kernel. You're probably facing some wrong install. Therefore, this has been tested and working fine with Big Sure even since first beta and hundreds of user reported zero problem like this..,

In any case, this is for report issues with the open source version, steps to reproduce, logs, etc., not for support on pro version, so please, write directly to the account provided inside the Gumroad receipt so I can help you find the issue, if any, with the app.

Thanks and best regards.
