### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by bknaepen** [rugarciap/Turbo-Boost-Switcher#165]
Hello,

What are the instructions to uninstall Turbo-Boost-Switcher ?

Thanks for any help,

Bernard.

**Comment by rugarciap** [comment]
Hi

Just drag & drop the .app to the trash.

Best.

**Comment by bknaepen** [comment]
Thanks !

**Comment by sunabozu** [comment]
How about the driver? It's still there.

**Comment by Ale-zen** [comment]
Hallo, how can I remove all the extensions too. Thanks
I have several kernel panic due to Turboboost Swithcher Pro, and after reboot system blocked the extension "Legacy Developer: Rugarciap"

**Comment by rugarciap** [comment]
The kext is activated on demand, and the system blocks the extension until you aprove it, that's why you see the "Legacy developer: rugarciap".. you need to go to your system settings to allow it. 

The kernel panic shows ALL kext loaded in the system, and usually turbo boost one is displayed first because it's loaded on demand.. it's not permanent and that's why you only need to send the app to the trash. If the app is not running, then the kext is not loaded. If the kext is loaded and you see it on the kernel panic as (last loaded kext), then it means the kext was loaded fine and it's not causing any issue.. in fact, in all of these years, in never caused to any user unless you have a Intel Mac that has no turbo boost...

That being said, going to remove this comment since it's about pro version and the information you're writing is just not ok. If you need further help, you an reach me at the support address provided with your purchase. This is for reporting issues with the free version.

Best.
