### ISSUE TITLE
TBS does not disable Turbo Boost on MacOS 11.6

### ISSUE THREAD

**Issue by bfeist** [rugarciap/Turbo-Boost-Switcher#174]
I updated to 11.6 and TBS Pro no longer works. Please advise.

**Comment by rugarciap** [comment]
Hi!

No worries, the app (both free and pro) works fine in 11.6 and also with current Monterey beta. Just remember to reboot after updating, since that's mandatory from macOS 11.3 (https://github.com/rugarciap/Turbo-Boost-Switcher/issues/163) 

If you keep having issues after this, please reach me at my contact inbox email for more support.

Best!

**Comment by bfeist** [comment]
Thanks so much. I didn't think to reboot after all the rebooting that occurred during the OS upgrade. Rebooting has fixed the issue.
And thank you for making this tool. It has become critical to making my i9 MacbookPro15,1 useable. The fans used to run continuously without TBS.
