### ISSUE TITLE
Turbo boost switcher pro not running

### ISSUE THREAD

**Issue by Operator2024** [rugarciap/Turbo-Boost-Switcher#178]
Hello, I have a MacBook air 2020 (intel) and Turbo Boost switcher pro does not want to run on it, but Turbo boost switcher free is run [Video](https://www.youtube.com/watch?v=QFfiYJCaeQE)

**Comment by rugarciap** [comment]
Hi,

This is for reporting issues with the free version of the app. No worries, the app works fine with all macOS versions released so far, but in order to get additional support, you can reach me at the email provided. You can also try the troubleshooting guide included with the app on the HELP option.

Thanks.
