### ISSUE TITLE
M1 version!

### ISSUE THREAD

**Issue by Eliasjahmil** [rugarciap/Turbo-Boost-Switcher#188]
I think there might be an issue with the part of accepting the blocked request tab in system settings. It didn't show up on my brother's M1 mac but it show up on mine like it was supposed to. maybe because his is M1 not intel. please make a M1 version

**Comment by rugarciap** [comment]
Hi there!

Turbo Boost is an Intel® only feature, so it's not available on Apple® chips anymore. In order to get a similar feature on those kind of macs, you can use the new low power mode, and if you want to, enable / disable it by using another app just released called Power Mode Switcher with more features to come in the mid term. 

You can find it at [www.pmswitcher.com](http://www.pmswitcher.com)

Enjoy!

**Comment by Eliasjahmil** [comment]
Thanks for letting me know, and I am looking for a performance boost too,
is that possible? Not just the low power mode
