### ISSUE TITLE
Unexpected Wake from Sleep with App Running

### ISSUE THREAD

**Issue by sjgrall** [rugarciap/Turbo-Boost-Switcher#189]
I have been experiencing unexpected wakes from sleep with the Turbo Boost Switcher app running, even when set to full manual mode. Quitting the app resolves the issue. This occurred both on macOS Monterey and macOS Ventura, though I suspect it could affect earlier OSes as well. My Mac is a 2019 16" MacBook Pro. Is this a known issue? Due to the issue, I've temporarily stopped using the app.

The wakes from sleep typically occur within 30-60 seconds after putting the Mac to sleep manually. If it goes back to sleep on its own, it usually stays asleep from that point on, until the next sleep cycle is initiated.

**Comment by rugarciap** [comment]
Hi!

The app doesn't perform any task while sleeping... in fact, no app can do that. Instead, depending on your power nap configuration, the mac will wake up apps periodically to perform background tasks if any.. so maybe that's the issue. I'd suggest to take a look to power nap configuration and disable that.

Best.

**Comment by sjgrall** [comment]
I turned off Power Nap. I am a Mac engineer professionally. But closing this ticket without further investigation has given me the answer I need.

**Comment by rugarciap** [comment]
Hi,

Closed because this is for reporting issues with the free version in a repeteable way, logs, ask for improvements, etc. For individual support, you can reach me at anytime using the contact methods you've got at the help for each free and pro version, faqs, email provided with the receipt if you've got the pro version, and so on.

Best.
