### ISSUE TITLE
Does turbo boost switcher still work?

### ISSUE THREAD

**Issue by AlexNabokikh** [rugarciap/Turbo-Boost-Switcher#191]
Hi,
I apologize if this question appears to be trivial, but I have noticed that the application seems to not be functioning properly. Specifically, I have observed that the Turbo Boost feature is not being disabled as intended. I initially suspected that the issue may have been on my end, but even after performing a complete re-installation of the operating system on my Mac, the problem persists. I attempted to load the kernel extension manually, however, the approval prompt never appears in the "Privacy & Security" settings.
```bash
❯ sudo kextutil -v /Applications/tbswitcher_resources/DisableTurboBoost.64bits.kext
Defaulting to kernel file '/System/Library/Kernels/kernel'
Executing: /usr/bin/kmutil load --bundle-path /Applications/tbswitcher_resources/DisableTurboBoost.64bits.kext
Error Domain=KMErrorDomain Code=27 "Extension with identifiers com.rugarciap.DisableTurboBoost not approved to load. Please approve using System Preferences." UserInfo={NSLocalizedDescription=Extension with identifiers com.rugarciap.DisableTurboBoost not approved to load. Please approve using System Preferences.}
```
The machine details:
MacBook Pro with 2,3 GHz Quad-Core Intel Core i7
Ventura 13.2
Turbo Boost Switcher Pro v2.12.0.

Thank you!

**Comment by rugarciap** [comment]
Hi,

Yes, it works, but macOS sometimes has issues with kernel extensions approvals. In fact, they have even provided some commands to remove all kext cachés and authorisations in order to ask for them again starting from scratch.

Please, refer to the help file included with the app with some guides to this kind of issues, and if the problem persist, reach me at the email provided with your pro version receipt for additional support if needed.

Best!
