### ISSUE TITLE
macOS Sonoma

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [rugarciap/Turbo-Boost-Switcher#200]
The current version is not working with the newest macOS Sonoma.

Any ideas why?

**Comment by rugarciap** [comment]
Hi!

The app works fine with Sonoma since the first beta. More info here: https://www.rugarciap.com/2023/06/tbs-working-on-macos-sonoma/

In fact it has been also verified with the current release candidate version. Did you try rebooting? this is mandatory after upgrading OS. 

You can take a look also to the help file included with the binaries and, if none of that works, feel free to reach me directly for additional support!

Best!
