### ISSUE TITLE
System crash while boost disabled

### ISSUE THREAD

**Issue by turannul** [rugarciap/Turbo-Boost-Switcher#202]
Hw: MacBook Pro 2019 (15,4) 13" 
OS: macOS 14.0 (23A344) & 14.1 (23B73)
When the battery runs out when plugged in, (unable to wake from sleep) it reboots.

Log attached
[panic-full-2023-10-20-230238.0003.txt](https://github.com/rugarciap/Turbo-Boost-Switcher/files/13059234/panic-full-2023-10-20-230238.0003.txt)

**Comment by rugarciap** [comment]
Hi,

This is not due to Turbo Boost Switcher. It only appears in the log since it's a kernel extension, and macOS logs every kext loaded in the system when collecting info after a crash. In fact, the log shows the kext was successfully loaded.

Googling around there are a lot of people with this issue... , like this thread https://forums.macrumors.com/threads/macos-catalina-10-15-3-crash-panic-cpu-0-caller-0xffffff801faa2d1c-sleep-transition-timed-out-after-180-seconds-while-calling-power-state-change.2227077/

Best.

**Comment by turannul** [comment]
> https://forums.macrumors.com/threads/macos-catalina-10-15-3-crash-panic-cpu-0-caller-0xffffff801faa2d1c-sleep-transition-timed-out-after-180-seconds-while-calling-power-state-change.2227077/

Thanks for reference, I checked PowerNap was already disabled. so that's not my issue
