### ISSUE TITLE
Trying to verify if turbo boost is actually disabled.

### ISSUE THREAD

**Issue by supersophie** [rugarciap/Turbo-Boost-Switcher#38]
Hi, 

I've been using TurboBoostSwitch for a month on macos 10.12.4 and now with 10.12.5

Apart from loading extension, how can I verify that Turbo Boost is actually disabled on macos?

With TurboBoostSwicther set to Disable the notebook CPU temperature regularly reached 85% and gets far too hot to use.  This is particularly evident when playing Eveonline.com. The notebook is too hot to touch and fan speed is maximum. 

Should the CPU reach such high temperatures when Turbo Boost is disabled?

How does the kernel extension disable Turbo Boost? What proof is there of this?  

Kind regards.

**Comment by rugarciap** [comment]
Hi

Unlike in linux where you can read msr values directly from /dev folder, in OSX there is no way to read MSR values directly, you need to use privileged APIs to access them, that's why there is a kernel extension included in the app, to enable / disable the corresponding Turbo Boost MSR flag:

http://www.intel.com/content/www/us/en/processors/architectures-software-developer-manuals.html

Lowering down CPU Temp, FAN speed are side effects of disabling Turbo Boost and the effect depends on lots of factors like software running, environment temperature and so on.

You can also read the README, section How to know if Turbo Boost is enabled or not..., I suggest you to use the Geekbench option and / or also the Intel Power gadget tool.

Best.

**Comment by supersophie** [comment]
Hi,

Thanks for your explanation.

The Intel Power tool no longer works on MacOS. I have tried several releases and they do not run. on 10.12 and 

Regards.
--

**Comment by supersophie** [comment]
Hi, 

Shows a difference with the app enabled and not, which is good :)  

With TurboBoost switch _not_ running
https://browser.geekbench.com/v4/cpu/2951778

Single-Core Score	Multi-Core Score
3144				5981

With Turboboost switch running and Turboboost set to Disabled
https://browser.geekbench.com/v4/cpu/2951825 <https://browser.geekbench.com/v4/cpu/2951825>Single-Core Score	Multi-Core Score
2115				4135

Somehow I have to have the EVE client to throttle down. Runs in WINE.

Regards.
