### ISSUE TITLE
2016 13‘ rMBP,  Can not login mac with TouchID 

### ISSUE THREAD

**Issue by HarweyWong** [rugarciap/Turbo-Boost-Switcher#49]
I can not log in with TouchID once activated Turbo-Boost-Switcher, neither can I when turn the Turbo off.
Does this only happen to my Mac ?
and any solutions ？
thanks very much

**Comment by rugarciap** [comment]
Hi!

TBS uses standard API to authorise the user to launch a privileged operation, so that's weird, it should work the same way as you enter user and password info.

No user has reported issues with touch id using PRO version neither, may be due to the authorisation is made different there, but will take a look in any case..., when I'm able to get a Mac with TouchID for myself :D . Hope sooner than later ;)

Set the issue as enhancement. In the meantime, you can also try to run the app as root with sudo.., plenty of info around about how to do it ;).

Thanks for your feedback and best regards.

**Comment by HarweyWong** [comment]
I‘ll try, hope that it would not appear again.
Thanks a lot for your work ~

**Comment by HarweyWong** [comment]
Anyone who got the same issue as me  just use $sudo ./Turbo\ Boost\ Switcher\ Pro.app/Contents/MacOS/Turbo\ Boost\ Switcher\ Pro in the terminal.
One little question, why I didn't need to use terminal to give authorization before ~

**Comment by HarweyWong** [comment]
I used ‘$ sudo Turbo\ Boost\ Switcher.app/Contents/MacOS/Turbo\ Boost\ Switcher’, but it can't work.
The terminal printed:
`Code Signing Failure: not code signed
Authentication Failures: 
    File owner/permissions are incorrect (must be root:wheel, nonwritable by group/other): `
Need I change into user 'root' to run app? 
One more question, why I don't need terminal and SU with the app of same version  before ?  Is it because HighSierra change the authorization policy?

**Comment by rugarciap** [comment]
Hi there, 

Just saw you edited your entry containing PRO logs..., this is for free and open source version.

Regarding your questions.

1.- No, you don't need to be root.., that's why the app asks for user and password and uses Authorisation APIs

2.- Again, NO, you don't need to open the terminal and run the app as ROOT. That was just a suggestion for you in order to try.

Closing this entry since it has evolved to a support question and can create confussion since contains wrong info. If you want to know more about how the app internally run just take a look at the source, the comments, the README, and the blog where all is deeply described ;).

Thanks.

**Comment by davibe** [comment]
Turbo boost Switcher keeps requesting me to type the password every time i resume from sleep. I would like to this with touchid. It is not clear to me if this is possible and what it takes. Can somebody explain ? this issue/question is not clear to me
