### ISSUE TITLE
Incorrect temperature value in comparison to Intel Power Gadget

### ISSUE THREAD

**Issue by JulyIGHOR** [rugarciap/Turbo-Boost-Switcher#54]
![image](https://user-images.githubusercontent.com/3390357/42328486-a3c97fee-806e-11e8-81c5-fce751d0d2d9.png)

**Comment by rugarciap** [comment]
Hi!

Thanks for your feedback.

Intel Power Gadget shows Package Temperature, and Turbo Boost Switcher displays CPU Temperature using Apple SMC Api like many other apps does. That's why you're seeing differences, because the apps display different sensor values. There are a lot of other temp sensors by the way...

[https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Intel_Power_Gadget](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Intel_Power_Gadget)

Here you can see an screenshot displaying same temperature of other popular app (smcFanControl).

![captura](https://user-images.githubusercontent.com/3028855/42347844-72d4dce2-80a7-11e8-99b2-dc4033ccec0a.png)

**Comment by JulyIGHOR** [comment]
This is from Macs Fan Control
![image](https://user-images.githubusercontent.com/3390357/42347978-ec9316ca-80a7-11e8-9e0e-e59573127e5b.png)

**Comment by rugarciap** [comment]
Thanks again for your feedback. As you can see, there are a lot of different values but the app (and other ones) just display one value, the first available for CPU Temps using SMC.

Just added a feature request (other users has requested that too) so in the future individual readings are displayed for multiple cores.

Best.

**Comment by JulyIGHOR** [comment]
Thanks for your time and reading this.
Also I have feature request: Disable Turbo Boost on some cooler RPM value, and enable if it become lower.

**Comment by rugarciap** [comment]
I've tested that in the past and almost included on a release, but the problem is the fan speed changes too fast and Turbo Boost becomes enabled / disabled too many times on a short period of time..., that's why I finally released an "alert" feature based on fan speed.

In any case, will think again about that in the future..., since I also want that for myself :D, but I need to think more about it to get a user friendly solution.

**Comment by JulyIGHOR** [comment]
example if max cooler RPM is 6000:
1) turn off turbo boost if RPM higher than 4000 instantly
2) turn on turbo boost if RPM lower than 3500 AND last turn off elapsed more than 2 minutes

the same for CPU temperature
