### ISSUE TITLE
Cannot disable TB despite following install instructions precisely

### ISSUE THREAD

**Issue by bwbang** [rugarciap/Turbo-Boost-Switcher#84]
I'm a huge fan of this app to try to eek out as much battery from my Macbook so hopefullly you can help me out.

- Downloaded TBS 2.7.1 
- Running OSX 10.13.6
- After unzipping, moved TBS app to the desktop
- Went to security to allow kext authorization
- Put in user password when TBS prompted me to
- Rebooted before installation
- Rebooted several times after installation
- Uninstalled and reinstalled several times
- Cannot get TBS to disable
- Ideas?

**Comment by rugarciap** [comment]
Hi,

Well, you missed some step for sure, since the app works fine with all macOS versions released so far. 

You can also execute in the terminal “kextstat” and search for the extension (com.rugarciap…). If it’s loaded then it means TB is off, refresh the icon by clicking over the menu...

You can also try:

1.- Stop / Quit the app.
2.- Drag to the trash the .app file.
3.- Open the original .zip and install the app again by dragging it to Applications folder (this step is very important…, if you run the app directly from the unziped folder will not work due to translocation).
4.- When asked, enter your root password.
5.- Click on “Disable Turbo Boost” manually to force the kext to load. If still “On”, go to Security prefs and allow the kext to be loaded.
7.- Try refreshing the status bar by clicking over it.

Please, take a look at this too, it’s all here:

https://www.rugarciap.com/faqs
https://www.rugarciap.com/2016/08/how-to-run-turbo-boost-switcher-on-macos-sierra/
https://www.rugarciap.com/2017/09/an-update-after-macos-high-sierra-release/

Best.

**Comment by bwbang** [comment]
I just uninstalled and reinstalled and followed steps 1-7 to a tee. Previously, I followed your FAQ install instructions precisely and the readme file that came with the zipped folder.
I also did a kextstat search in terminal and com.rugarciap was not loaded even after hitting Allow in the security panel many times.
To make sure the status bar was refreshed I toggled dark/light menu bar settings.
TBS cannot be disabled.

**Comment by rugarciap** [comment]
Hi,

Just tried on that os version and worked fine. In order to help, provide steps to reproduce and system logs when trying to enable / disable turbo boost. The more info the better.

Besides, you mention "even after hitting Allow in the security panel many times.". Well, that's not possible, since "allow request" is only displayed once, as you can see also on Apple documentation: https://developer.apple.com/library/archive/technotes/tn2459/_index.html 

Best.

**Comment by rugarciap** [comment]
I see.., You're getting the kext approval request.., but after clicking allow you need to try to load the kext again by clicking on disable Turbo Boost again ;) ., you can try also by quiting and opening the app again...

You're almost there..., if it doesn't work it'd be another thing, not the app.., In example, you can't allow kexts if using screen sharing tools and other limitations introduced by Apple on Sierra.

Best!
