### ISSUE TITLE
"Disable Turbo Boost" requires to be pressed twice in order to work

### ISSUE THREAD

**Issue by foxnoodles** [rugarciap/Turbo-Boost-Switcher#98]
here's the scenario:
Each time my Mac wakes up from sleep Turbo Boost Switcher asks for a password. 
Entering the password does not automatically disable the Turbo Boost. Instead, I have to disable it manually by clicking "Disable Turbo Boost", but it never works for the first time. I have to click it again and then it works. 

Also, Disable TB at launch option does not work either. Turbo Boost is always on and I have to switch it manually (by clicking twice). 

Late 2015 Mac Book pro 15'  2.5ghz core i7 
OS: 10.14.5

**Comment by earglass** [comment]
Hi!

Same here, but from MacBook Pro 13-inch, 2017.
Also Mojave, 10.14.5.

Is this only happening on Free version? I was considering purchasing Pro but if it happens there as well, I'm not gonna - it's super annoying. 

I also tried running it as sudo, password entries are gone of course but problem with TB enabled after each suspension is there, double click issue is there, also disabling at launch doesn't work. All I managed to do is after 3 days of suspending/resuming system, I managed to hang this app completely and I had to reboot because it was no longer able to start after crashing.

Any logs I can provide to help?

**Comment by foxnoodles** [comment]
Mine is a free version as well.

The only workaround(kinda) I've found is to cancel the first password prompt (by clicking cancel or hitting an escape key), the prompt will come back in a sec and that's when I enter the password. That way turbo boost state stays unchanged.

**Comment by rugarciap** [comment]
Hi!

Please, take a look at this.., it's all explained there: [https://github.com/rugarciap/Turbo-Boost-Switcher/issues/4](https://github.com/rugarciap/Turbo-Boost-Switcher/issues/4)

In summary, this is due to how Apple manages authorisation timeouts and yes, the PRO version doesn't need to fill the root password after long period of inactivity time.

**Comment by foxnoodles** [comment]
I don't think that #4 is relevant to this issue. Or it's something I don't understand and would like to know. Because fixing the password prompt by wrapping it with an AppleScript or a custom .plist file doesn't fix the problem described in my post. 
"turbo boost" gets enabled and in order to disable it you are required to click the "disable turbo boost" menu item Twice, not once but Twice because the first click simply does nothing, no matter what(with or without AppleScript wrapper or .plist file which just fix the recurring password prompt issue)

**Comment by berezovskyi** [comment]
> clicking "Disable Turbo Boost", but it never works for the first time. I have to click it again and then it works.

I have the same issue regarding the two clicks. #4 fix was applied too, so it does not matter (as @foxnoodles correctly pointed out) and I was not asked for a password - I just had to select the option twice. Verified with Power Gadget.

**Comment by earglass** [comment]
FYI - this is solved on paid version. It's due to how mac works with helper applications.

**Comment by foxnoodles** [comment]
Solve in paid version and not in Free one? So that is now considered as a "Premium feature"? Nice.
