### ISSUE TITLE
Lack of macOS Catalina Beta support

### ISSUE THREAD

**Issue by PiotrMielcarzewicz** [rugarciap/Turbo-Boost-Switcher#99]
It looks like that on macOS Catalina Beta 10.15 this app doesn't work. Are you planning to fix it soon or you'll release an update in the fall, when the catalina will officially launch?

**Comment by rugarciap** [comment]
Hi!

Thanks for your feedback. macOS Catalina hasn’t been released yet. There’s a beta available for testing, and as expected, it contains bugs.

One of them is preventing the kernel extension the app uses from being loaded. This also happened on macOS Mojave first betas. It’s commented here: https://forums.developer.apple.com/thread/118301

I’ve also reported the bug to Apple through https://feedbackassistant.apple.com , and it would be great if you also report it (that’s what betas are good for ;).., the more people reporting it the more chance they decide to fix it soon….I guess. 

You can use the info of the previous forum post if you need to, or run from terminal “sudo kextutil -v /path/to/app/Contents/Resources/DisableTurboBoost.64bits.kext” and send the output to Apple.

In the meantime, as a workaround, you can disable SIP in order to run the app on macOS Catalina beta until they decide to fix it… hope so! but at the end, is up to them... but the app will work in any case on Catalina final release without disabling SIP if they fix that.., or disabling SIP if they don't.

**Comment by lcdtyph** [comment]
The kext issue has been fixed in the latest catalina beta(19A536g).

**Comment by rugarciap** [comment]
Yeah, thanks! Also verified myself yesterday..., will update descriptions to let all people know :).
